//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnerMetrixWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GetGuestDimensionalBalanceScore
    {
        public string OracleId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<System.DateTime> DateAssessmentStarted { get; set; }
        public Nullable<System.DateTime> DateTokenUsed { get; set; }
        public string Token { get; set; }
        public string Name { get; set; }
        public double Score { get; set; }
        public string Sign { get; set; }
    }
}
