//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnerMetrixWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Score
    {
        public long ID { get; set; }
        public decimal Score1 { get; set; }
        public long Attribute { get; set; }
        public long Token { get; set; }
    
        public virtual Attribute Attribute1 { get; set; }
        public virtual Token Token1 { get; set; }
    }
}
