//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnerMetrixWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Token
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Token()
        {
            this.CategoryScores = new HashSet<CategoryScore>();
            this.DimensionalBalanceScores = new HashSet<DimensionalBalanceScore>();
            this.ReliabilityScores = new HashSet<ReliabilityScore>();
            this.Scores = new HashSet<Score>();
            this.ValuationScores = new HashSet<ValuationScore>();
        }
    
        public long ID { get; set; }
        public Nullable<long> GuestId { get; set; }
        public string Token1 { get; set; }
        public Nullable<bool> IsUsed { get; set; }
        public Nullable<int> TokenStatus { get; set; }
        public Nullable<System.DateTime> DateLocked { get; set; }
        public Nullable<System.DateTime> DateUsed { get; set; }
        public Nullable<bool> IsLocked { get; set; }
        public string ScoresUrl { get; set; }
        public string Lang { get; set; }
        public Nullable<bool> IsArchived { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoryScore> CategoryScores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimensionalBalanceScore> DimensionalBalanceScores { get; set; }
        public virtual Guest Guest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReliabilityScore> ReliabilityScores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Score> Scores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ValuationScore> ValuationScores { get; set; }
    }
}
